title: My Page
author: Kirsten
email: entzk@mcmaster.ca
description: > # this means to ignore newlines until "baseurl:"
  This is my page!
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
